### ISSUE TITLE
Solver2.0 whitelist

### ISSUE THREAD

**Issue by tnissen** [SalvusHub/salvus_mesher#9]
Input from mesher:

- other parameters: https://github.com/martinvandriel/axisem2.0/blob/master/doc/mesh_file_format_2.0.txt
- (an)elastic parameters  on 2D GLL mesh slice(s) ((an)isotropic parameters, coordinate system?)

Optional pre-processing for complex models (2.5D,3D) may modify elastic parameters from mesher.
output: model plots for paraview, courant, elements per wavelength. 

Input for simulation:
- Source depth, mechanism (for 3D structure), moment-tensor/force?
- Receiver depth/lat/lon (coordinate system?)
- seismogram length

Submit script:
- flag elements for output based on source-receiver input
- save reproducible settings: locally modified code? use diff *f90

Output: 
- Data: instaseisDB for flagged elements, xdmf descriptor files
- wavefields for plotting (same as kernel wavefields (i.e. instaseisDB)
- energy

Solver: 
- choices: 1D/3D (complex numbers for all cases?), time schemes
- development: avoid duplications in stiffness term (4 sources simultaneously?), ABC (smart layers?), generalise solid-fluid, ocean + fluid free-surface BC, generalise order of non-blocking communication (halo first), 

Post-processing: 
- stress, strain

Future extensions: ellipticity, gravity

Test cases:

**Comment by martinvandriel** [comment]
This relates to the solver, so closing it here
